from __future__ import annotations

import logging
from contextlib import contextmanager
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Iterator, Mapping, Sequence

from sqlalchemy import create_engine, event, text
from sqlalchemy.engine import Connection, CursorResult, Engine
from sqlalchemy.exc import IntegrityError as DatabaseIntegrityError
from sqlalchemy.pool import StaticPool


SCHEMA_VERSION = 8
logger = logging.getLogger("xiaoasi_mail_gateway.database")


class DatabaseResult:
    """统一 SQLAlchemy 查询结果，向业务层返回可按字段名读取的行。"""

    def __init__(self, result: CursorResult[Any]) -> None:
        self._result = result

    @property
    def rowcount(self) -> int:
        return int(self._result.rowcount or 0)

    def fetchone(self) -> Mapping[str, Any] | None:
        return self._result.mappings().fetchone()

    def fetchall(self) -> list[Mapping[str, Any]]:
        return list(self._result.mappings().fetchall())

    def __iter__(self):
        return iter(self.fetchall())


class DatabaseConnection:
    """将项目原有问号占位 SQL 转换为 SQLAlchemy 命名参数。"""

    def __init__(self, connection: Connection) -> None:
        self._connection = connection

    @staticmethod
    def _prepare(
        sql: str,
        params: Sequence[Any] | Mapping[str, Any] | None,
    ) -> tuple[str, Mapping[str, Any]]:
        if params is None:
            return sql, {}
        if isinstance(params, Mapping):
            return sql, params

        values = list(params)
        expected = sql.count("?")
        if expected != len(values):
            raise ValueError(f"SQL 参数数量不匹配: 占位符 {expected}，参数 {len(values)}")
        pieces = sql.split("?")
        bindings = {f"p{index}": value for index, value in enumerate(values)}
        converted = pieces[0]
        for index, piece in enumerate(pieces[1:]):
            converted += f":p{index}{piece}"
        return converted, bindings

    def execute(
        self,
        sql: str,
        params: Sequence[Any] | Mapping[str, Any] | None = None,
    ) -> DatabaseResult:
        statement, bindings = self._prepare(sql, params)
        return DatabaseResult(self._connection.execute(text(statement), bindings))

    def executescript(self, script: str) -> None:
        for statement in script.split(";"):
            if statement.strip():
                self._connection.execute(text(statement))


class GatewayDatabase:
    """负责 PostgreSQL/SQLite 连接、事务和结构初始化。生产环境使用 PostgreSQL。"""

    def __init__(self, url_or_path: str | Path) -> None:
        raw_value = str(url_or_path)
        self.url = self._normalize_url(raw_value)
        self.engine = self._create_engine(self.url)
        self.dialect_name = self.engine.dialect.name

    @staticmethod
    def _normalize_url(value: str) -> str:
        if value == ":memory:":
            return "sqlite+pysqlite:///:memory:"
        if "://" not in value:
            path = Path(value)
            path.parent.mkdir(parents=True, exist_ok=True)
            return "sqlite+pysqlite:///" + path.resolve().as_posix()
        if value.startswith("postgresql://"):
            return "postgresql+psycopg://" + value.removeprefix("postgresql://")
        return value

    @staticmethod
    def _create_engine(url: str) -> Engine:
        if url == "sqlite+pysqlite:///:memory:":
            engine = create_engine(
                url,
                connect_args={"check_same_thread": False},
                poolclass=StaticPool,
            )
        elif url.startswith("sqlite"):
            engine = create_engine(url, connect_args={"check_same_thread": False})
        else:
            engine = create_engine(
                url,
                pool_pre_ping=True,
                pool_size=10,
                max_overflow=20,
                pool_timeout=15,
                pool_recycle=1800,
            )

        if url.startswith("sqlite"):
            @event.listens_for(engine, "connect")
            def configure_sqlite(dbapi_connection, _connection_record) -> None:
                cursor = dbapi_connection.cursor()
                cursor.execute("PRAGMA foreign_keys = ON")
                cursor.execute("PRAGMA busy_timeout = 10000")
                if url != "sqlite+pysqlite:///:memory:":
                    cursor.execute("PRAGMA journal_mode = WAL")
                cursor.close()

        return engine

    @contextmanager
    def transaction(self) -> Iterator[DatabaseConnection]:
        with self.engine.begin() as connection:
            yield DatabaseConnection(connection)

    @contextmanager
    def read(self) -> Iterator[DatabaseConnection]:
        with self.engine.connect() as connection:
            yield DatabaseConnection(connection)

    def initialize(self) -> None:
        id_definition = (
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            if self.dialect_name == "postgresql"
            else "INTEGER PRIMARY KEY AUTOINCREMENT"
        )
        with self.transaction() as connection:
            connection.executescript(
                f"""
                CREATE TABLE IF NOT EXISTS gateway_schema (
                    version INTEGER NOT NULL
                );

                CREATE TABLE IF NOT EXISTS cloudmail_instances (
                    id {id_definition},
                    name TEXT NOT NULL UNIQUE,
                    base_url TEXT NOT NULL,
                    admin_email TEXT NOT NULL,
                    admin_password_encrypted TEXT NOT NULL,
                    proxy_url TEXT NOT NULL DEFAULT '',
                    verify_tls INTEGER NOT NULL DEFAULT 1,
                    enabled INTEGER NOT NULL DEFAULT 1,
                    health_status TEXT NOT NULL DEFAULT 'unknown',
                    last_checked_at TEXT,
                    last_error TEXT NOT NULL DEFAULT '',
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL
                );

                CREATE TABLE IF NOT EXISTS mail_domains (
                    id {id_definition},
                    instance_id BIGINT NOT NULL REFERENCES cloudmail_instances(id) ON DELETE CASCADE,
                    domain TEXT NOT NULL UNIQUE,
                    enabled INTEGER NOT NULL DEFAULT 1,
                    weight INTEGER NOT NULL DEFAULT 100 CHECK(weight BETWEEN 1 AND 10000),
                    status TEXT NOT NULL DEFAULT 'unknown',
                    failure_count INTEGER NOT NULL DEFAULT 0,
                    cooldown_until TEXT,
                    last_used_at TEXT,
                    success_count INTEGER NOT NULL DEFAULT 0,
                    failure_total INTEGER NOT NULL DEFAULT 0,
                    remark TEXT NOT NULL DEFAULT '',
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL
                );

                CREATE TABLE IF NOT EXISTS mailboxes (
                    id TEXT PRIMARY KEY,
                    address TEXT NOT NULL UNIQUE,
                    owner_user_id BIGINT,
                    domain_id BIGINT NOT NULL REFERENCES mail_domains(id),
                    instance_id BIGINT NOT NULL REFERENCES cloudmail_instances(id),
                    purpose TEXT NOT NULL DEFAULT '',
                    source TEXT NOT NULL DEFAULT '',
                    status TEXT NOT NULL DEFAULT 'active',
                    verification_status TEXT NOT NULL DEFAULT 'pending',
                    verification_code TEXT NOT NULL DEFAULT '',
                    provider_reference TEXT NOT NULL DEFAULT '',
                    pop_enabled INTEGER NOT NULL DEFAULT 1,
                    created_at TEXT NOT NULL,
                    expires_at TEXT,
                    updated_at TEXT NOT NULL
                );

                CREATE TABLE IF NOT EXISTS idempotency_records (
                    idempotency_key TEXT PRIMARY KEY,
                    user_id BIGINT,
                    request_hash TEXT NOT NULL,
                    request_fingerprint TEXT NOT NULL DEFAULT '',
                    mailbox_id TEXT NOT NULL REFERENCES mailboxes(id) ON DELETE CASCADE,
                    status TEXT NOT NULL DEFAULT 'completed',
                    created_at TEXT NOT NULL,
                    expires_at TEXT NOT NULL
                );

                CREATE TABLE IF NOT EXISTS gateway_request_logs (
                    id {id_definition},
                    request_id TEXT NOT NULL,
                    endpoint TEXT NOT NULL,
                    method TEXT NOT NULL,
                    source TEXT NOT NULL DEFAULT '',
                    user_id BIGINT,
                    mailbox_id TEXT,
                    instance_id BIGINT,
                    domain_id BIGINT,
                    status_code INTEGER NOT NULL,
                    duration_ms INTEGER NOT NULL DEFAULT 0,
                    error_code TEXT NOT NULL DEFAULT '',
                    error_message TEXT NOT NULL DEFAULT '',
                    created_at TEXT NOT NULL
                );

                CREATE TABLE IF NOT EXISTS admin_sessions (
                    token_hash TEXT PRIMARY KEY,
                    username TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    expires_at TEXT NOT NULL,
                    last_seen_at TEXT NOT NULL
                );

                CREATE TABLE IF NOT EXISTS admin_audit_logs (
                    id {id_definition},
                    admin_user_id BIGINT,
                    username TEXT NOT NULL,
                    action TEXT NOT NULL,
                    target_type TEXT NOT NULL DEFAULT '',
                    target_id TEXT NOT NULL DEFAULT '',
                    detail TEXT NOT NULL DEFAULT '',
                    request_id TEXT NOT NULL DEFAULT '',
                    source_ip TEXT NOT NULL DEFAULT '',
                    created_at TEXT NOT NULL
                );

                CREATE TABLE IF NOT EXISTS users (
                    id {id_definition},
                    username TEXT NOT NULL UNIQUE,
                    email TEXT UNIQUE,
                    password_hash TEXT NOT NULL,
                    role TEXT NOT NULL DEFAULT 'user' CHECK(role IN ('admin', 'user')),
                    status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active', 'disabled')),
                    user_auth_code TEXT,
                    user_auth_code_hash TEXT,
                    user_auth_code_updated_at TEXT,
                    admin_pop_auth_code TEXT,
                    admin_pop_auth_code_hash TEXT,
                    admin_pop_auth_code_updated_at TEXT,
                    pop_enabled INTEGER NOT NULL DEFAULT 1,
                    pop_failed_attempts INTEGER NOT NULL DEFAULT 0,
                    pop_locked_until TEXT,
                    last_pop_login_at TEXT,
                    credit_balance BIGINT NOT NULL DEFAULT 0 CHECK(credit_balance >= 0),
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL
                );

                CREATE TABLE IF NOT EXISTS user_api_keys (
                    id {id_definition},
                    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    name TEXT NOT NULL,
                    key_prefix TEXT NOT NULL,
                    key_hash TEXT NOT NULL UNIQUE,
                    api_key TEXT,
                    enabled INTEGER NOT NULL DEFAULT 1,
                    last_used_at TEXT,
                    created_at TEXT NOT NULL,
                    revoked_at TEXT
                );

                CREATE TABLE IF NOT EXISTS user_sessions (
                    session_hash TEXT PRIMARY KEY,
                    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    role TEXT NOT NULL CHECK(role IN ('admin', 'user')),
                    created_at TEXT NOT NULL,
                    expires_at TEXT NOT NULL,
                    last_seen_at TEXT NOT NULL,
                    revoked_at TEXT
                );

                CREATE TABLE IF NOT EXISTS user_registration_codes (
                    id TEXT PRIMARY KEY,
                    email TEXT NOT NULL,
                    code_hash TEXT NOT NULL,
                    consumed INTEGER NOT NULL DEFAULT 0,
                    attempts INTEGER NOT NULL DEFAULT 0,
                    created_at TEXT NOT NULL,
                    expires_at TEXT NOT NULL
                );

                CREATE TABLE IF NOT EXISTS credit_rules (
                    operation TEXT PRIMARY KEY,
                    cost_points BIGINT NOT NULL DEFAULT 0 CHECK(cost_points >= 0),
                    initial_user_points BIGINT NOT NULL DEFAULT 0 CHECK(initial_user_points >= 0),
                    updated_by BIGINT REFERENCES users(id),
                    updated_at TEXT NOT NULL
                );

                CREATE TABLE IF NOT EXISTS credit_transactions (
                    id {id_definition},
                    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    type TEXT NOT NULL CHECK(type IN ('consume', 'refund', 'admin_adjust')),
                    status TEXT NOT NULL CHECK(status IN ('pending', 'completed', 'reversed')),
                    amount BIGINT NOT NULL,
                    balance_after BIGINT NOT NULL CHECK(balance_after >= 0),
                    reference_type TEXT NOT NULL DEFAULT '',
                    reference_id TEXT NOT NULL DEFAULT '',
                    remark TEXT NOT NULL DEFAULT '',
                    created_at TEXT NOT NULL
                );

                CREATE TABLE IF NOT EXISTS credit_packages (
                    id {id_definition},
                    slug TEXT NOT NULL UNIQUE,
                    name TEXT NOT NULL,
                    points BIGINT NOT NULL CHECK(points > 0),
                    price BIGINT NOT NULL DEFAULT 0 CHECK(price >= 0),
                    purchase_url TEXT NOT NULL DEFAULT '',
                    enabled INTEGER NOT NULL DEFAULT 1,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL
                );

                CREATE TABLE IF NOT EXISTS credit_cdks (
                    id {id_definition},
                    package_id BIGINT NOT NULL REFERENCES credit_packages(id),
                    code TEXT NOT NULL UNIQUE,
                    points BIGINT NOT NULL CHECK(points > 0),
                    status TEXT NOT NULL DEFAULT 'unused'
                        CHECK(status IN ('unused', 'redeemed', 'disabled')),
                    generated_by BIGINT REFERENCES users(id),
                    redeemed_by BIGINT REFERENCES users(id),
                    redeemed_at TEXT,
                    disabled_at TEXT,
                    disabled_by BIGINT REFERENCES users(id),
                    batch_id TEXT NOT NULL DEFAULT '',
                    created_at TEXT NOT NULL
                );
                """
            )
            current = connection.execute("SELECT version FROM gateway_schema LIMIT 1").fetchone()
            if current is None:
                connection.execute("INSERT INTO gateway_schema(version) VALUES (0)")
                current_version = 0
            else:
                current_version = int(current["version"])

            if current_version > SCHEMA_VERSION:
                raise RuntimeError(f"不支持的 Gateway 数据库版本: {current_version}")

            if self.dialect_name == "postgresql":
                connection.execute(
                    "ALTER TABLE mailboxes ADD COLUMN IF NOT EXISTS verification_code TEXT NOT NULL DEFAULT ''"
                )
                connection.execute(
                    "ALTER TABLE mailboxes ADD COLUMN IF NOT EXISTS owner_user_id BIGINT"
                )
                connection.execute(
                    "ALTER TABLE mailboxes ADD COLUMN IF NOT EXISTS pop_enabled INTEGER NOT NULL DEFAULT 1"
                )
                connection.execute(
                    "ALTER TABLE idempotency_records ADD COLUMN IF NOT EXISTS user_id BIGINT"
                )
                connection.execute(
                    "ALTER TABLE idempotency_records ADD COLUMN IF NOT EXISTS request_fingerprint TEXT NOT NULL DEFAULT ''"
                )
                connection.execute(
                    "ALTER TABLE idempotency_records ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'completed'"
                )
                connection.execute(
                    "ALTER TABLE gateway_request_logs ADD COLUMN IF NOT EXISTS user_id BIGINT"
                )
                connection.execute(
                    "ALTER TABLE admin_audit_logs ADD COLUMN IF NOT EXISTS admin_user_id BIGINT"
                )
                connection.execute(
                    "ALTER TABLE admin_audit_logs ADD COLUMN IF NOT EXISTS request_id TEXT NOT NULL DEFAULT ''"
                )
                connection.execute(
                    "ALTER TABLE admin_audit_logs ADD COLUMN IF NOT EXISTS source_ip TEXT NOT NULL DEFAULT ''"
                )
                connection.execute(
                    "ALTER TABLE users ADD COLUMN IF NOT EXISTS admin_pop_auth_code TEXT"
                )
                connection.execute(
                    "ALTER TABLE users ADD COLUMN IF NOT EXISTS user_auth_code TEXT"
                )
                connection.execute(
                    "ALTER TABLE user_api_keys ADD COLUMN IF NOT EXISTS api_key TEXT"
                )
            else:
                mailbox_columns = {
                    str(row["name"])
                    for row in connection.execute("PRAGMA table_info(mailboxes)").fetchall()
                }
                if "verification_code" not in mailbox_columns:
                    connection.execute(
                        "ALTER TABLE mailboxes ADD COLUMN verification_code TEXT NOT NULL DEFAULT ''"
                    )
                if "owner_user_id" not in mailbox_columns:
                    connection.execute("ALTER TABLE mailboxes ADD COLUMN owner_user_id BIGINT")
                if "pop_enabled" not in mailbox_columns:
                    connection.execute("ALTER TABLE mailboxes ADD COLUMN pop_enabled INTEGER NOT NULL DEFAULT 1")

                idempotency_columns = {
                    str(row["name"])
                    for row in connection.execute("PRAGMA table_info(idempotency_records)").fetchall()
                }
                if "user_id" not in idempotency_columns:
                    connection.execute("ALTER TABLE idempotency_records ADD COLUMN user_id BIGINT")
                if "request_fingerprint" not in idempotency_columns:
                    connection.execute(
                        "ALTER TABLE idempotency_records ADD COLUMN request_fingerprint TEXT NOT NULL DEFAULT ''"
                    )
                if "status" not in idempotency_columns:
                    connection.execute(
                        "ALTER TABLE idempotency_records ADD COLUMN status TEXT NOT NULL DEFAULT 'completed'"
                    )

                request_log_columns = {
                    str(row["name"])
                    for row in connection.execute("PRAGMA table_info(gateway_request_logs)").fetchall()
                }
                if "user_id" not in request_log_columns:
                    connection.execute("ALTER TABLE gateway_request_logs ADD COLUMN user_id BIGINT")

                audit_columns = {
                    str(row["name"])
                    for row in connection.execute("PRAGMA table_info(admin_audit_logs)").fetchall()
                }
                if "admin_user_id" not in audit_columns:
                    connection.execute("ALTER TABLE admin_audit_logs ADD COLUMN admin_user_id BIGINT")
                if "request_id" not in audit_columns:
                    connection.execute("ALTER TABLE admin_audit_logs ADD COLUMN request_id TEXT NOT NULL DEFAULT ''")
                if "source_ip" not in audit_columns:
                    connection.execute("ALTER TABLE admin_audit_logs ADD COLUMN source_ip TEXT NOT NULL DEFAULT ''")

                user_columns = {
                    str(row["name"])
                    for row in connection.execute("PRAGMA table_info(users)").fetchall()
                }
                if "admin_pop_auth_code" not in user_columns:
                    connection.execute("ALTER TABLE users ADD COLUMN admin_pop_auth_code TEXT")
                if "user_auth_code" not in user_columns:
                    connection.execute("ALTER TABLE users ADD COLUMN user_auth_code TEXT")

                api_key_columns = {
                    str(row["name"])
                    for row in connection.execute("PRAGMA table_info(user_api_keys)").fetchall()
                }
                if "api_key" not in api_key_columns:
                    connection.execute("ALTER TABLE user_api_keys ADD COLUMN api_key TEXT")

            connection.executescript(
                """
                CREATE INDEX IF NOT EXISTS idx_domains_instance ON mail_domains(instance_id);
                CREATE INDEX IF NOT EXISTS idx_mailboxes_created ON mailboxes(created_at DESC);
                CREATE INDEX IF NOT EXISTS idx_request_logs_created ON gateway_request_logs(created_at DESC);
                CREATE INDEX IF NOT EXISTS idx_admin_sessions_expires ON admin_sessions(expires_at);
                CREATE UNIQUE INDEX IF NOT EXISTS uq_users_admin_role ON users(role) WHERE role='admin';
                CREATE INDEX IF NOT EXISTS idx_user_api_keys_user ON user_api_keys(user_id, enabled);
                CREATE INDEX IF NOT EXISTS idx_user_sessions_user ON user_sessions(user_id, expires_at);
                CREATE INDEX IF NOT EXISTS idx_user_registration_codes_email
                    ON user_registration_codes(email, created_at DESC);
                CREATE INDEX IF NOT EXISTS idx_user_registration_codes_expires
                    ON user_registration_codes(expires_at);
                CREATE INDEX IF NOT EXISTS idx_credit_transactions_user ON credit_transactions(user_id, created_at DESC);
                CREATE INDEX IF NOT EXISTS idx_credit_packages_enabled ON credit_packages(enabled, id);
                CREATE INDEX IF NOT EXISTS idx_credit_cdks_status ON credit_cdks(status, created_at DESC);
                CREATE INDEX IF NOT EXISTS idx_credit_cdks_package ON credit_cdks(package_id, status, created_at DESC);
                CREATE INDEX IF NOT EXISTS idx_credit_cdks_redeemed_by ON credit_cdks(redeemed_by, redeemed_at DESC);
                CREATE INDEX IF NOT EXISTS idx_mailboxes_owner ON mailboxes(owner_user_id, created_at DESC);
                CREATE INDEX IF NOT EXISTS idx_request_logs_user ON gateway_request_logs(user_id, created_at DESC);
                CREATE INDEX IF NOT EXISTS idx_admin_audit_created ON admin_audit_logs(created_at DESC);
                """
            )
            connection.execute(
                """INSERT INTO credit_rules(operation, cost_points, initial_user_points, updated_at)
                VALUES ('create_mailbox', 1, 0, ?)
                ON CONFLICT(operation) DO NOTHING""",
                (datetime.now(UTC).isoformat(),),
            )
            now = datetime.now(UTC).isoformat()
            connection.execute(
                """INSERT INTO credit_packages
                (slug, name, points, price, purchase_url, enabled, created_at, updated_at)
                VALUES ('default-1000', '1000积分', 1000, 0, 'https://pay.ldxp.cn/item/9z9op3', 1, ?, ?)
                ON CONFLICT(slug) DO NOTHING""",
                (now, now),
            )
            connection.execute(
                """INSERT INTO credit_packages
                (slug, name, points, price, purchase_url, enabled, created_at, updated_at)
                VALUES ('default-10000', '10000积分', 10000, 0, 'https://pay.ldxp.cn/item/vjxbeh', 1, ?, ?)
                ON CONFLICT(slug) DO NOTHING""",
                (now, now),
            )
            connection.execute(
                """UPDATE credit_packages SET purchase_url=?, updated_at=?
                WHERE slug='default-1000' AND purchase_url=''""",
                ('https://pay.ldxp.cn/item/9z9op3', now),
            )
            connection.execute(
                """UPDATE credit_packages SET purchase_url=?, updated_at=?
                WHERE slug='default-10000' AND purchase_url=''""",
                ('https://pay.ldxp.cn/item/vjxbeh', now),
            )
            connection.execute("UPDATE gateway_schema SET version = ?", (SCHEMA_VERSION,))
            if current_version != SCHEMA_VERSION:
                logger.info(
                    "gateway_database_schema_upgraded dialect=%s from=%s to=%s",
                    self.dialect_name,
                    current_version,
                    SCHEMA_VERSION,
                )

    def dispose(self) -> None:
        self.engine.dispose()


__all__ = ["DatabaseIntegrityError", "GatewayDatabase"]
