from __future__ import annotations

import logging
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Iterator, Mapping, Sequence

from sqlalchemy import create_engine, event, text
from sqlalchemy.engine import Connection, CursorResult, Engine
from sqlalchemy.exc import IntegrityError as DatabaseIntegrityError
from sqlalchemy.pool import StaticPool


SCHEMA_VERSION = 3
logger = logging.getLogger("xiaoasi_mail_gateway.database")


class DatabaseResult:
    """统一 SQLAlchemy 查询结果，向业务层返回可按字段名读取的行。"""

    def __init__(self, result: CursorResult[Any]) -> None:
        self._result = result

    @property
    def rowcount(self) -> int:
        return int(self._result.rowcount or 0)

    def fetchone(self) -> Mapping[str, Any] | None:
        return self._result.mappings().fetchone()

    def fetchall(self) -> list[Mapping[str, Any]]:
        return list(self._result.mappings().fetchall())

    def __iter__(self):
        return iter(self.fetchall())


class DatabaseConnection:
    """将项目原有问号占位 SQL 转换为 SQLAlchemy 命名参数。"""

    def __init__(self, connection: Connection) -> None:
        self._connection = connection

    @staticmethod
    def _prepare(
        sql: str,
        params: Sequence[Any] | Mapping[str, Any] | None,
    ) -> tuple[str, Mapping[str, Any]]:
        if params is None:
            return sql, {}
        if isinstance(params, Mapping):
            return sql, params

        values = list(params)
        expected = sql.count("?")
        if expected != len(values):
            raise ValueError(f"SQL 参数数量不匹配: 占位符 {expected}，参数 {len(values)}")
        pieces = sql.split("?")
        bindings = {f"p{index}": value for index, value in enumerate(values)}
        converted = pieces[0]
        for index, piece in enumerate(pieces[1:]):
            converted += f":p{index}{piece}"
        return converted, bindings

    def execute(
        self,
        sql: str,
        params: Sequence[Any] | Mapping[str, Any] | None = None,
    ) -> DatabaseResult:
        statement, bindings = self._prepare(sql, params)
        return DatabaseResult(self._connection.execute(text(statement), bindings))

    def executescript(self, script: str) -> None:
        for statement in script.split(";"):
            if statement.strip():
                self._connection.execute(text(statement))


class GatewayDatabase:
    """负责 PostgreSQL/SQLite 连接、事务和结构初始化。生产环境使用 PostgreSQL。"""

    def __init__(self, url_or_path: str | Path) -> None:
        raw_value = str(url_or_path)
        self.url = self._normalize_url(raw_value)
        self.engine = self._create_engine(self.url)
        self.dialect_name = self.engine.dialect.name

    @staticmethod
    def _normalize_url(value: str) -> str:
        if value == ":memory:":
            return "sqlite+pysqlite:///:memory:"
        if "://" not in value:
            path = Path(value)
            path.parent.mkdir(parents=True, exist_ok=True)
            return "sqlite+pysqlite:///" + path.resolve().as_posix()
        if value.startswith("postgresql://"):
            return "postgresql+psycopg://" + value.removeprefix("postgresql://")
        return value

    @staticmethod
    def _create_engine(url: str) -> Engine:
        if url == "sqlite+pysqlite:///:memory:":
            engine = create_engine(
                url,
                connect_args={"check_same_thread": False},
                poolclass=StaticPool,
            )
        elif url.startswith("sqlite"):
            engine = create_engine(url, connect_args={"check_same_thread": False})
        else:
            engine = create_engine(
                url,
                pool_pre_ping=True,
                pool_size=10,
                max_overflow=20,
                pool_timeout=15,
                pool_recycle=1800,
            )

        if url.startswith("sqlite"):
            @event.listens_for(engine, "connect")
            def configure_sqlite(dbapi_connection, _connection_record) -> None:
                cursor = dbapi_connection.cursor()
                cursor.execute("PRAGMA foreign_keys = ON")
                cursor.execute("PRAGMA busy_timeout = 10000")
                if url != "sqlite+pysqlite:///:memory:":
                    cursor.execute("PRAGMA journal_mode = WAL")
                cursor.close()

        return engine

    @contextmanager
    def transaction(self) -> Iterator[DatabaseConnection]:
        with self.engine.begin() as connection:
            yield DatabaseConnection(connection)

    @contextmanager
    def read(self) -> Iterator[DatabaseConnection]:
        with self.engine.connect() as connection:
            yield DatabaseConnection(connection)

    def initialize(self) -> None:
        id_definition = (
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            if self.dialect_name == "postgresql"
            else "INTEGER PRIMARY KEY AUTOINCREMENT"
        )
        with self.transaction() as connection:
            connection.executescript(
                f"""
                CREATE TABLE IF NOT EXISTS gateway_schema (
                    version INTEGER NOT NULL
                );

                CREATE TABLE IF NOT EXISTS cloudmail_instances (
                    id {id_definition},
                    name TEXT NOT NULL UNIQUE,
                    base_url TEXT NOT NULL,
                    admin_email TEXT NOT NULL,
                    admin_password_encrypted TEXT NOT NULL,
                    proxy_url TEXT NOT NULL DEFAULT '',
                    verify_tls INTEGER NOT NULL DEFAULT 1,
                    enabled INTEGER NOT NULL DEFAULT 1,
                    health_status TEXT NOT NULL DEFAULT 'unknown',
                    last_checked_at TEXT,
                    last_error TEXT NOT NULL DEFAULT '',
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL
                );

                CREATE TABLE IF NOT EXISTS mail_domains (
                    id {id_definition},
                    instance_id BIGINT NOT NULL REFERENCES cloudmail_instances(id) ON DELETE CASCADE,
                    domain TEXT NOT NULL UNIQUE,
                    enabled INTEGER NOT NULL DEFAULT 1,
                    weight INTEGER NOT NULL DEFAULT 100 CHECK(weight BETWEEN 1 AND 10000),
                    status TEXT NOT NULL DEFAULT 'unknown',
                    failure_count INTEGER NOT NULL DEFAULT 0,
                    cooldown_until TEXT,
                    last_used_at TEXT,
                    success_count INTEGER NOT NULL DEFAULT 0,
                    failure_total INTEGER NOT NULL DEFAULT 0,
                    remark TEXT NOT NULL DEFAULT '',
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL
                );

                CREATE TABLE IF NOT EXISTS mailboxes (
                    id TEXT PRIMARY KEY,
                    address TEXT NOT NULL UNIQUE,
                    domain_id BIGINT NOT NULL REFERENCES mail_domains(id),
                    instance_id BIGINT NOT NULL REFERENCES cloudmail_instances(id),
                    purpose TEXT NOT NULL DEFAULT '',
                    source TEXT NOT NULL DEFAULT '',
                    status TEXT NOT NULL DEFAULT 'active',
                    verification_status TEXT NOT NULL DEFAULT 'pending',
                    verification_code TEXT NOT NULL DEFAULT '',
                    provider_reference TEXT NOT NULL DEFAULT '',
                    created_at TEXT NOT NULL,
                    expires_at TEXT,
                    updated_at TEXT NOT NULL
                );

                CREATE TABLE IF NOT EXISTS idempotency_records (
                    idempotency_key TEXT PRIMARY KEY,
                    request_hash TEXT NOT NULL,
                    mailbox_id TEXT NOT NULL REFERENCES mailboxes(id) ON DELETE CASCADE,
                    created_at TEXT NOT NULL,
                    expires_at TEXT NOT NULL
                );

                CREATE TABLE IF NOT EXISTS gateway_request_logs (
                    id {id_definition},
                    request_id TEXT NOT NULL,
                    endpoint TEXT NOT NULL,
                    method TEXT NOT NULL,
                    source TEXT NOT NULL DEFAULT '',
                    mailbox_id TEXT,
                    instance_id BIGINT,
                    domain_id BIGINT,
                    status_code INTEGER NOT NULL,
                    duration_ms INTEGER NOT NULL DEFAULT 0,
                    error_code TEXT NOT NULL DEFAULT '',
                    error_message TEXT NOT NULL DEFAULT '',
                    created_at TEXT NOT NULL
                );

                CREATE TABLE IF NOT EXISTS admin_sessions (
                    token_hash TEXT PRIMARY KEY,
                    username TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    expires_at TEXT NOT NULL,
                    last_seen_at TEXT NOT NULL
                );

                CREATE TABLE IF NOT EXISTS admin_audit_logs (
                    id {id_definition},
                    username TEXT NOT NULL,
                    action TEXT NOT NULL,
                    target_type TEXT NOT NULL DEFAULT '',
                    target_id TEXT NOT NULL DEFAULT '',
                    detail TEXT NOT NULL DEFAULT '',
                    created_at TEXT NOT NULL
                );

                CREATE TABLE IF NOT EXISTS gateway_client_keys (
                    id {id_definition},
                    name TEXT NOT NULL UNIQUE,
                    api_key TEXT NOT NULL UNIQUE,
                    enabled INTEGER NOT NULL DEFAULT 1,
                    last_used_at TEXT,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL
                );
                """
            )
            current = connection.execute("SELECT version FROM gateway_schema LIMIT 1").fetchone()
            if current is None:
                connection.execute("INSERT INTO gateway_schema(version) VALUES (0)")
                current_version = 0
            else:
                current_version = int(current["version"])

            if current_version > SCHEMA_VERSION:
                raise RuntimeError(f"不支持的 Gateway 数据库版本: {current_version}")

            if self.dialect_name == "postgresql":
                connection.execute(
                    "ALTER TABLE mailboxes ADD COLUMN IF NOT EXISTS verification_code TEXT NOT NULL DEFAULT ''"
                )
            else:
                mailbox_columns = {
                    str(row["name"])
                    for row in connection.execute("PRAGMA table_info(mailboxes)").fetchall()
                }
                if "verification_code" not in mailbox_columns:
                    connection.execute(
                        "ALTER TABLE mailboxes ADD COLUMN verification_code TEXT NOT NULL DEFAULT ''"
                    )

            connection.executescript(
                """
                CREATE INDEX IF NOT EXISTS idx_domains_instance ON mail_domains(instance_id);
                CREATE INDEX IF NOT EXISTS idx_mailboxes_created ON mailboxes(created_at DESC);
                CREATE INDEX IF NOT EXISTS idx_request_logs_created ON gateway_request_logs(created_at DESC);
                CREATE INDEX IF NOT EXISTS idx_admin_sessions_expires ON admin_sessions(expires_at);
                CREATE INDEX IF NOT EXISTS idx_client_keys_enabled ON gateway_client_keys(enabled);
                """
            )
            connection.execute("UPDATE gateway_schema SET version = ?", (SCHEMA_VERSION,))
            if current_version != SCHEMA_VERSION:
                logger.info(
                    "gateway_database_schema_upgraded dialect=%s from=%s to=%s",
                    self.dialect_name,
                    current_version,
                    SCHEMA_VERSION,
                )

    def dispose(self) -> None:
        self.engine.dispose()


__all__ = ["DatabaseIntegrityError", "GatewayDatabase"]
